runtime: nodejs20 
instance_class: F1
entrypoint: node index.js
env_variables:
  SENDGRID_API_KEY: "your_sendgrid_api_key" 
  GOOGLE_MAPS_API_KEY: "your_google_maps_api_key" 
  GOOGLE_CLOUD_PROJECT: "you_google_cloud_project_api" #REPLACE
  HQ_LAT: "xx.xxxx" # your warehouse latitude
  HQ_LNG: "xx.xxxx" # your warehouse longitude


handlers:
  - url: /.*
    script: auto
